### ISSUE TITLE
Требования, пункт 3

### ISSUE THREAD

**Issue by AJIOB** [FieryBird1504/ToDaTS#2]
В [данном](https://github.com/FieryBird1504/ToDaTS/blob/master/Dark%20Rooms.md#3-%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D1%8B%D0%B5-%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) пункте требуется описать "требования к продукту описанные на уровне достаточном для однозначного понимания того, как система может быть спроектирована и протестирована на предмет удовлетворения данных требований", а не требования к системе конечного пользователя. Поэтому требования к системе конечного пользователя рекомендуется перенести в пункт 3.2.2 "Ограничения", предварительно создав его

**Comment by FieryBird1504** [comment]
Fixed

**Comment by AJIOB** [comment]
В каком коммите?
